### ISSUE TITLE
Selecting caravan in world view locks up game

### ISSUE THREAD

**Issue by TheMattMan2751** [rvanasa/rimworld-cities#13]
With RimCities enabled, selecting a caravan in the world view causes all elements to disappear from the screen (apart from terrain in cursor). Attempting to reload with F9 (RimSaves) causes RimWorld to completely crash

**Comment by RetroCobalt** [comment]
When I test the caravan in world map, seems to work. Do you have an error log that shows the error?

**Comment by TheMattMan2751** [comment]
Looks like [v0.4.10](https://github.com/rvanasa/rimworld-cities/commit/da49da11d74e866fb297b396194a2c280ca89489) fixed this, closing the issue
