### ISSUE TITLE
Stop Asking Me to Betray Allies

### ISSUE THREAD

**Issue by killerx243** [rvanasa/rimworld-cities#24]
Would it be possible to have an option to prevent quests where you're doing a hostile action against friendly cities and instead have those quests spawn on enemy cities even if they are farther away? I have a really close nation that has cities and they are my closest ally and city quests only get generated for them. Why on earth would I want to destroy my allies defences or help their prisoners escape? It makes sense that I might do an assassination (since that can be done without triggering relation loss and fake politics).

**Comment by rvanasa** [comment]
This is fixed in the 1.3 version of RimCities. Cheers!
